[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "79v3xvzmEcbuAhp5NDkJRNDNR8a6EMimRTSD5HgC57kf"
puppet-master = "3qeZRjNWndSk2sVgGDdmLmfk3fQEr9APD1QQuTgf4tTC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
