[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet_master = "3Z9WEGXY1V7RC5yEsCxyr7F9iS7mpm4rn4hzMrQnZanJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
